// Generated by typings
// Source: https://raw.githubusercontent.com/types/npm-domready/20df138f0d5de36e2663dc4ff8bb5d98fc8f7639/domready.d.ts
declare module 'domready' {
function domready(callback: () => any): void;

export = domready;
}
